---
title : "데이터 과학"
author : "오태환"
date: "3/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 데이터 사이언스 입문 … 얻고자 하는 것...

-  데이터를 다루는 기본적인 능력과 센스
- 데이터를 어떻게 실제로 이용해서 유의미한 것을 도출하는지 배우고 싶습니다.
- 프로젝트를 통한 데이터 분석 능력 향상, 
데이터 사이언스가 되기 위해선 무엇이 필요한지 배우고, 수업이 끝나고 스스로 공부할 수 있는 기초 확립
- 데이터 사이언스가 적용되고 있는 분야와 실제로 활용하기 위해 필요한 기술, 응용을 위해 쌓아야 하는 기초 지식은 어떤 것들이 있는지
- 단순히 이론적인 범위를 벗어나서 실제 프로젝트를 진행함으로써, 사회문제를 조망해보고 싶었습니다.
- 실제 난해한 데이터를 정리하는 능력기르기. ex) 함수 만들기. 다양한방법으로 쉽게, 유전자 데이터 분석 등 
- 지금까지는 단편적인 분석 기법들만 배워봤는데 전체적인 프로젝트를 함께 진행하면서 흐름을 알아보고 싶습니다
- 머신러닝 뿐 아니라 만들어진 모델을 웹에 올리고 배포하는 과정까지 체험해볼 수 있을 과목인 것 같아 수강신청하게 었습니다. 
- 데이터 사이언스를 실제 프로젝트를 진행하면서 구현해보고 싶습니다.
- 개발을 해보고 싶습니다
- 실제 프로젝트를 통한 데이터 분석 능력을 향상, R프로그래밍을 좀 더 전문적으로 사용
AI관련 인지심리 지식을 데이터사이언스와 융합시키기 위해 데이터사이언스 기초를 배우고 싶습니다.
- 데이터 분석이 실무에 어떻게 적용되는지 직접 체험해보고 싶습니다. 
- 데이터사이언스에 대해 개략적으로나마 알아가고싶습니다.

# 도대체 데이터 사이언스 무엇이냐?
- [데이터 과학 입문](https://statkclee.github.io/data-science/ds-education.html)
- https://home.kpmg/kr/ko/home/insights/2020/03/issue-monitor-121.html


다양한 형태의 데이터에서 여러 분야의 협업을 통해 인사이트와 지식을 얻어내는 것
의사결정을 위해 데이터를 수집하고, 그 데이터를 분석하여 의사결정에 필요한 정보를 도출하는 과정
방대한 양의 데이터 분석을 통해 유용한/필요한 정보를 얻어내는 것
데이터에 숨겨진 정보를 찾는 기술
도처에 널려있는 여러가지 정보를 취합하고 의미를 부여하여 가치를 창출하는것. 
데이터 분석으로 의사결정 과정에 유의미한 정보를 제공한는 방법
데이터를 수집하고 처리하여 이를 바탕으로 유의미한 정보를 분석해내는 방법
데이터를 통해 새로운 정보를 얻을 수 있는 방법을 배우는 학문이라고 생각합니다.
데이터에서 필요한 정보를 추출하여 새로운 인사이트를 얻어내는 기술
데이터로부터 가치를 창출할 수 있는 인사이트를 도출하기 위한 일련의 기술
데이터를 수집하는 것부터 시작해서 의미있는 의사결정을 하기까지의 모든 과정
데이터 안에 숨겨진 공통적인 성질을 파악해 시각화를 해서 의미를 찾아내는 것
데이터를 분석하여 유의미한 인사이트를 얻어내는 과정
거대한 양의 데이터를 분석하여 가치를 장출해내는 것
데이터를 활용하여 유의미한 정보를 도출해내기 위한 기술 및 분석 과정

데이터 과학자가 만드는 제품과 서비스는 무엇일까요?

개인의 직관이 아닌 데이터를 통한 의사결정
빅데이터 기반으로 사용자 맞춤 광고
자동화/추천 시스템 등 사용자의 편의를 증진시키는 서비스

방대한 데이터를 활용한 예측 모델
기존 데이터를 활용하여 어떤 모델을 만들어서 새로운 값을 입력하면 그에 따른 출력결과를 보여주는 제품을 만들 수 있다고 생각합니다. 
정리되지 않은 데이터에 대한 정보 추출
알고리즘을 통해서 미래를 예측할 수 있는 도구 제공

빅데이터를 이용해서 자동화, 추천시스템, 예측 모델 등을 만들고 있습니다. 구글의 번역 시스템이나 검색어 자동입력 시스템을 예로 들 수 있습니다. 
직관적으로 현상을 이해하도록, 경향을 파악하도록, 하는 무언가? 
사진 변환 필터링 (ex. 고흐, 뭉크, 클림트 버전 등등)
최신 트렌드를 따라가는 제품을 만들어 사람들의 선호도가 높은 제품
오류가 최소화된 알고리듬 및 예측모델
패턴
자동화 제품

